export const SET_TOKEN = 'SET_TOKEN';
export const SET_AUTH = 'SET_AUTH';
export const SET_USER = 'SET_USER';
export const SET_ANIMALS = 'SET_ANIMALS';
export const ADD_FAV_ANIMAL = 'ADD_FAV_ANIMAL';
export const DEL_FAV_ANIMAL = 'DEL_FAV_ANIMAL';
export const ADD_FAV_ANIMALS = 'ADD_FAV_ANIMALS';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_ANIMAL = 'CHANGE_ANIMAL';
export const SET_ANIMAL = 'SET_ANIMAL';
export const CHANGE_BREED = 'CHANGE_BREED';


export const COMMENTS_ACTION_TYPES = {
    ADD_COMMENT: 'ADD_COMMENT',
    SET_COMMENTS: 'SET_COMMENTS',
    IS_LOADING: 'IS_LOADING',
    FETCH_COMMENTS_FAILED: 'FETCH_COMMENTS_FAILED'
}
