export const SET_ANIMALS = 'SET_ANIMALS';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_ANIMAL = 'CHANGE_ANIMAL';
export const CHANGE_BREED = 'CHANGE_BREED';